### PR TITLE
migrate to use tsup

### PR DESCRIPTION
**Pull request by ndelangen**
I changed the build system to use ts-up..

I think the documentation needs to be changed considerably, and we also need to check if it actually all works.

### CODE REVIEW

**Review by winkerVSbecks — APPROVED** [review]
thanks @ndelangen!

**Comment by winkerVSbecks** [comment]
@ndelangen [esbuild@0.15.1](https://socket.dev/npm/package/esbuild/overview/0.15.1) has a security warning. Can you use a newer version?

**Comment by ndelangen** [comment]
Do not merge yet, @yannbf will look this over!

**Comment by yannbf** [comment]
So sorry for the ultra late reply, I'll take a look at this tomorrow

**Comment by winkerVSbecks** [comment]
@yannbf @ndelangen any updates on this?

**Comment by ndelangen** [comment]
@yannbf how do I test this works?

**Comment by ndelangen** [comment]
I added a workflow, but it's not running. No idea why..

**Comment by ndelangen** [comment]
Is actions disabled on this repo?
https://github.com/storybookjs/addon-kit/actions

**Comment by ndelangen** [comment]
Maybe because it's a repo template?

**Comment by ndelangen** [comment]
Turns out it was just disabled on the repo... I enabled it.

**Comment by ndelangen** [comment]
I think I did all I can, to make this go as green as possible. But it seems the CI wasn't setup at all / was disabled.

**Comment by winkerVSbecks** [comment]
closing in favour of #45

**Pull request closed without merging**
